Sln/Dayvo.Bubble/Dayvo.Bubble/Models/ErrorViewModel.cs
using System;

namespace Dayvo.Bubble.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sln/Dayvo.Bubble/Dayvo.Bubble/Controllers/Bubble/BubbleController.cs
using Dayvo.Negocio.BM.Bubble;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dayvo.Bubble.Controllers.Bubble
{
    public class BubbleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IEnumerable<string> OrderBurbuja(Boolean Asc, string Texto) {
            BMBubble bMBubble = new BMBubble();
            string[] txtNumb = Texto.Split(',');
            int[] numbers;
            numbers = new int[txtNumb.Length];
            for (int i = 0; i < txtNumb.Length; i++)
            {
                //Lista de Enteros
                numbers.SetValue(Convert.ToInt32(txtNumb.GetValue(i)), i);
            }
            IEnumerable<string> resultado;
            if (Asc)
            {
                resultado = bMBubble.SortAscending(numbers);
            }
            else {
                resultado = bMBubble.SortDescending(numbers);
            }
            return resultado;
        }
    }
}

Sln/Dayvo.Bubble/Dayvo.Bubble/Controllers/Columnas/ColumnasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dayvo.Bubble.Controllers.Columnas
{
    public class ColumnasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sln/Dayvo.Bubble/Dayvo.Bubble/Controllers/HomeController.cs
using Dayvo.Bubble.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Dayvo.Bubble.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sln/Dayvo.Bubble/Dayvo.Bubble/Controllers/Replicator/ReplicatorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Dayvo.Bubble.Controllers
{
    public class ReplicatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Sln/Dayvo.Bubble/Dayvo.Bubble/Views/Bubble/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<div>
    <label>Por favor ingrese los valores a ordenar separados por coma (,):</label>
    <input type="text" id="txtInput" />
</div>
<div>
    <label>Por favor seleccione el criterio de Ordenación: &nbsp; &nbsp; &nbsp;  </label>
    <input type="radio" class="k-primary" value="Ascendente" checked="checked" name="Criterio" id="Criterio" />Ascendente &nbsp; &nbsp;
    <input type="radio" class="k-primary" value="Descendente" name="Criterio" id="Descendente" />Descendente
</div>
<div>
    <label>Resultado:</label>
    <input type="text" id="txtResultado" disabled style="width:max-content; min-width:400px;"/>
</div>
<div>
    <button class="k-button k-primary" id="btnBubble">Ver Resultados Bubble</button>
</div>

<script src="~/js/Views/Bubble/Bubble.js"></script>

Sln/Dayvo.Bubble/Dayvo.Bubble/Views/Columnas/Index.cshtml
@{
    ViewData["Title"] = "Columnas";
}
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>

<h1>BOOSTRAP</h1>
<body>
    <div class="container">
        <div class="row m-2">
            <div class="col-lg-2 col-md-3 col-sm-12 bg-primary d-flex justify-content-center p-3">1</div>
            <div class="col-lg-2 col-md-3 col-sm-12 bg-warning d-flex justify-content-center p-3">2</div>
            <div class="col-lg-2 col-md-3 col-sm-12 bg-success d-flex justify-content-center p-3">3</div>
            <div class="col-lg-2 col-md-3 col-sm-12 bg-danger d-flex justify-content-center p-3">4</div>
            <div class="col-lg-2 col-md-6 col-sm-12 bg-info d-flex justify-content-center p-3">5</div>
            <div class="col-lg-2 col-md-6 col-sm-12 bg-secondary d-flex justify-content-center p-3">6</div>

        </div>
    </div>


</body>

Sln/Dayvo.Bubble/Dayvo.Bubble/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Sln/Dayvo.Bubble/Dayvo.Bubble/Views/Replicator/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Replicator</h1>

<label> Input Replicator: </label>
<input type="text" id="txtEntrada" style="width:300px"/>


<label id="lblMensaje"></label>
<div>
    <label>Replicated:</label>&nbsp;&nbsp;
    <input type="text" id="txtReplicado" style="width:300px" disabled/>
</div>


<div>
    <label id="lblCantidad">Amount of characters:</label>&nbsp;&nbsp;
    <input type="text" id="txtCantidad" style="width:300px" disabled/>
</div>

<div>
    <label>Consonants:</label>&nbsp;&nbsp;
    <input type="text" id="txtConsonants" style="width:350px" disabled />
</div>



<script src="~/js/Views/Replicator/Replicator.js"></script>

Sln/Dayvo.Bubble/Dayvo.Bubble/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dayvo.Bubble</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dayvo.Bubble</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bubble" asp-action="Index">Bubble</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Replicator" asp-action="Index">Replicator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Columnas" asp-action="Index">Columnas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Dayvo.Bubble - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>